import { AgentResults, LogLine } from '@/types';

export const mockLogs: LogLine[] = [
  { time: '00:01', message: '🔍 Cloning repository...' },
  { time: '00:03', message: '📂 Analyzing file structure — 12 files found' },
  { time: '00:07', message: '🧪 Running test suite inside Docker sandbox...' },
  { time: '00:12', message: '❌ 6 failures detected across 4 files' },
  { time: '00:14', message: '🤖 Generating targeted fixes with Claude AI...' },
  { time: '00:18', message: "✅ [AI-AGENT] Fix LINTING error in src/utils.py line 15: remove unused import 'os'" },
  { time: '00:20', message: '✅ [AI-AGENT] Fix SYNTAX error in src/validator.py line 8: add missing colon' },
  { time: '00:22', message: '✅ [AI-AGENT] Fix TYPE_ERROR in src/models/user.py line 34: cast str to int' },
  { time: '00:24', message: '✅ [AI-AGENT] Fix LOGIC error in src/processor.py line 52: fix off-by-one in loop' },
  { time: '00:26', message: '✅ [AI-AGENT] Fix IMPORT error in src/api/handlers.py line 3: add missing module' },
  { time: '00:28', message: '✅ [AI-AGENT] Fix INDENTATION error in src/config.py line 21: fix mixed tabs/spaces' },
  { time: '00:31', message: '🔁 Pushing branch RIFT_ORGANISERS_SAIYAM_KUMAR_AI_Fix to remote...' },
  { time: '00:35', message: '🔄 CI/CD Run #1 triggered — waiting for GitHub Actions...' },
  { time: '00:50', message: '❌ CI/CD Run #1 FAILED — 2 failures remaining' },
  { time: '00:52', message: '🤖 Generating additional fixes for remaining failures...' },
  { time: '00:58', message: '🔁 Pushing iteration 2 fixes...' },
  { time: '01:02', message: '🔄 CI/CD Run #2 triggered...' },
  { time: '01:14', message: '✅ CI/CD Run #2 PASSED — All tests green!' },
  { time: '01:16', message: '🎉 Agent complete! Final score: 110 pts in 1m 34s' },
];

export const mockResults: AgentResults = {
  run_id: 'demo-run-rift-2026',
  repo_url: 'https://github.com/rift2026/sample-broken-repo',
  team_name: 'RIFT ORGANISERS',
  leader_name: 'Saiyam Kumar',
  branch: 'RIFT_ORGANISERS_SAIYAM_KUMAR_AI_Fix',
  start_time: new Date(Date.now() - 154000).toISOString(),
  end_time: new Date().toISOString(),
  duration_seconds: 94,
  total_failures: 6,
  total_fixes: 6,
  total_commits: 6,
  final_status: 'PASSED',
  score: { base: 100, speed_bonus: 10, penalty: 0, total: 110 },
  fixes: [
    {
      file: 'src/utils.py',
      bug_type: 'LINTING',
      line_number: 15,
      commit_message: "[AI-AGENT] Fix LINTING error in src/utils.py line 15: remove unused import 'os'",
      status: 'FIXED',
    },
    {
      file: 'src/validator.py',
      bug_type: 'SYNTAX',
      line_number: 8,
      commit_message: '[AI-AGENT] Fix SYNTAX error in src/validator.py line 8: add missing colon',
      status: 'FIXED',
    },
    {
      file: 'src/models/user.py',
      bug_type: 'TYPE_ERROR',
      line_number: 34,
      commit_message: '[AI-AGENT] Fix TYPE_ERROR in src/models/user.py line 34: cast str to int',
      status: 'FIXED',
    },
    {
      file: 'src/processor.py',
      bug_type: 'LOGIC',
      line_number: 52,
      commit_message: '[AI-AGENT] Fix LOGIC error in src/processor.py line 52: fix off-by-one in loop',
      status: 'FIXED',
    },
    {
      file: 'src/api/handlers.py',
      bug_type: 'IMPORT',
      line_number: 3,
      commit_message: '[AI-AGENT] Fix IMPORT error in src/api/handlers.py line 3: add missing module path',
      status: 'FIXED',
    },
    {
      file: 'src/config.py',
      bug_type: 'INDENTATION',
      line_number: 21,
      commit_message: '[AI-AGENT] Fix INDENTATION error in src/config.py line 21: fix mixed tabs/spaces',
      status: 'FIXED',
    },
  ],
  cicd_runs: [
    {
      run_number: 1,
      timestamp: new Date(Date.now() - 76000).toISOString(),
      status: 'FAILED',
      failures_remaining: 2,
    },
    {
      run_number: 2,
      timestamp: new Date(Date.now() - 10000).toISOString(),
      status: 'PASSED',
      failures_remaining: 0,
    },
  ],
};
